"""
state.py

State used by the Live Coding workflow.

This state is separate from PlacementState because
coding sessions have their own lifecycle.
"""

from typing import List, Optional, Any

from pydantic import BaseModel, Field


# ==========================================================
# Code Snapshot
# ==========================================================

class CodeSnapshotState(BaseModel):
    """
    Represents a snapshot of the candidate's code.
    """

    code: str

    language: str = "cpp"

    trigger: Optional[str] = None

    timestamp: Optional[float] = None


# ==========================================================
# Execution State
# ==========================================================

class CodeExecutionState(BaseModel):
    """
    Represents one execution/submission.
    """

    code: str

    language: str

    passed: bool = False

    passed_tests: int = 0

    total_tests: int = 0

    stdout: Optional[str] = None

    stderr: Optional[str] = None

    error: Optional[str] = None

    execution_time_ms: Optional[float] = None

    memory_used_kb: Optional[float] = None


# ==========================================================
# Observation State
# ==========================================================

class CodingObservationState(BaseModel):
    """
    Represents something noticed about the candidate's
    coding behaviour or solution.
    """

    observation: str

    category: str

    severity: Optional[str] = None

    evidence: Optional[str] = None

    should_intervene: bool = False


# ==========================================================
# Interviewer Event
# ==========================================================

class InterviewerEventState(BaseModel):
    """
    Represents an intervention/question generated by
    the live coding interviewer.
    """

    question: str

    reason: str

    related_code: Optional[str] = None

    related_concept: Optional[str] = None

    # ------------------------------------------------------
    # Candidate response
    # ------------------------------------------------------

    candidate_answer: Optional[str] = None

    # ------------------------------------------------------
    # Answer evaluation
    # ------------------------------------------------------

    answer_quality: Optional[float] = None

    answer_correctness: Optional[float] = None

    answer_reasoning_quality: Optional[float] = None

    answer_evaluated: bool = False

    answer_feedback: Optional[str] = None

    answer_strengths: List[str] = Field(
        default_factory=list
    )

    answer_weaknesses: List[str] = Field(
        default_factory=list
    )

    follow_up_needed: bool = False

    follow_up_reason: Optional[str] = None


# ==========================================================
# Coding Session State
# ==========================================================

class CodingSessionState(BaseModel):
    """
    Runtime state of a live coding session.
    """

    # ------------------------------------------------------
    # Candidate
    # ------------------------------------------------------

    user_id: int

    session_id: Optional[int] = None

    # ------------------------------------------------------
    # Problem
    # ------------------------------------------------------

    problem_id: Optional[int] = None

    problem_title: Optional[str] = None

    problem_statement: Optional[str] = None

    category: Optional[str] = None

    difficulty: Optional[str] = None

    # ------------------------------------------------------
    # Session configuration
    # ------------------------------------------------------

    mode: str

    company: Optional[str] = None

    role: Optional[str] = None

    language: str = "cpp"

    duration_minutes: Optional[int] = None

    number_of_questions: Optional[int] = None

    # ------------------------------------------------------
    # Current editor state
    # ------------------------------------------------------

    current_code: str = ""

    previous_code: str = ""

    # ------------------------------------------------------
    # Execution
    # ------------------------------------------------------

    last_execution: Optional[
        CodeExecutionState
    ] = None

    executions: List[
        CodeExecutionState
    ] = Field(default_factory=list)

    # ------------------------------------------------------
    # Code history
    # ------------------------------------------------------

    snapshots: List[
        CodeSnapshotState
    ] = Field(default_factory=list)

    # ------------------------------------------------------
    # AI observations
    # ------------------------------------------------------

    observations: List[
        CodingObservationState
    ] = Field(default_factory=list)

    # ------------------------------------------------------
    # Interviewer
    # ------------------------------------------------------

    interviewer_events: List[
        InterviewerEventState
    ] = Field(default_factory=list)

    # ------------------------------------------------------
    # Current interviewer question
    # ------------------------------------------------------

    current_interviewer_question: Optional[
        InterviewerEventState
    ] = None

    # ------------------------------------------------------
    # Interview progress
    # ------------------------------------------------------

    interviewer_question_count: int = 0

    interviewer_answer_count: int = 0

    # ------------------------------------------------------
    # Dry run
    # ------------------------------------------------------

    dry_run_active: bool = False

    dry_run_data: Optional[Any] = None

    # ------------------------------------------------------
    # Session status
    # ------------------------------------------------------

    started: bool = False

    completed: bool = False

    submitted: bool = False

    # ------------------------------------------------------
    # Progress
    # ------------------------------------------------------

    current_question_number: int = 1